In [ ]:
import numpy as np

In [ ]:
# 第3题：生成数组并做 ufunc 加法（输出 result_3）
arr1 = np.arange(12)
np.random.shuffle(arr1)
arr1 = arr1.reshape(3, 4)           # 3x4
print("arr1 (3x4):\n", arr1)

arr2 = np.random.randn(16).reshape(4, 4)  # 4x4 正态分布
print("arr2 (4x4):\n", arr2)

arr1_t = arr1.T                     # 转置 -> 4x3
new_col = np.zeros((arr1_t.shape[0], 1))  # 4x1
arr1_expanded = np.hstack([arr1_t, new_col])  # 4x4
print("arr1 转置并扩充一列后 (4x4):\n", arr1_expanded)

result_3 = arr1_expanded + arr2
print("第3题结果 result_3 (4x4):\n", result_3)

arr1 (3x4):
 [[ 1  3 10  6]
 [ 0  5  9 11]
 [ 7  4  2  8]]
arr2 (4x4):
 [[ 0.48167199  1.41732984 -0.18412634  0.10552709]
 [-0.61555172  0.38067397 -0.53422424 -0.3476008 ]
 [-0.27915309  0.93446891 -0.07365184 -1.91343566]
 [ 1.25549027 -1.38849899  0.81501484 -0.68040489]]
arr1 转置并扩充一列后 (4x4):
 [[ 1.  0.  7.  0.]
 [ 3.  5.  4.  0.]
 [10.  9.  2.  0.]
 [ 6. 11.  8.  0.]]
第3题结果 result_3 (4x4):
 [[ 1.48167199  1.41732984  6.81587366  0.10552709]
 [ 2.38444828  5.38067397  3.46577576 -0.3476008 ]
 [ 9.72084691  9.93446891  1.92634816 -1.91343566]
 [ 7.25549027  9.61150101  8.81501484 -0.68040489]]


In [3]:
# 第4题：直接使用 result_3
repeated_result = np.repeat(result_3, 2, axis=1)  # 按列重复 2 次 -> (4,8)
print("按列重复后 shape:", repeated_result.shape)
print(repeated_result)

flattened = repeated_result.flatten()
unique_values = np.unique(flattened)
print("拉平并去重后的唯一值:\n", unique_values)

按列重复后 shape: (4, 8)
[[ 1.48167199  1.48167199  1.41732984  1.41732984  6.81587366  6.81587366
   0.10552709  0.10552709]
 [ 2.38444828  2.38444828  5.38067397  5.38067397  3.46577576  3.46577576
  -0.3476008  -0.3476008 ]
 [ 9.72084691  9.72084691  9.93446891  9.93446891  1.92634816  1.92634816
  -1.91343566 -1.91343566]
 [ 7.25549027  7.25549027  9.61150101  9.61150101  8.81501484  8.81501484
  -0.68040489 -0.68040489]]
拉平并去重后的唯一值:
 [-1.91343566 -0.68040489 -0.3476008   0.10552709  1.41732984  1.48167199
  1.92634816  2.38444828  3.46577576  5.38067397  6.81587366  7.25549027
  8.81501484  9.61150101  9.72084691  9.93446891]
